### ISSUE TITLE
code

### ISSUE THREAD

**Issue by aodarendeli** [okkyibrohim/id-multi-label-hate-speech-and-abusive-language-detection#1]
bro please share your code ???

**Comment by okkyibrohim** [comment]
Hi, thanks for the requests!
I plan for it, but until now don't have time to "tidy up" that code and publish it on this GitHub. In the meantime, you can easily re-implement my paper (https://aclanthology.org/W19-3506.pdf) for this dataset using Scikit-Learn Library and simply follow the default parameter given by them :)
